ARG ELK_VERSION=5.6.3
FROM docker.elastic.co/kibana/kibana:$ELK_VERSION
# https://github.com/elastic/kibana-docker

ARG ELK_VERSION
ENV ELK_VERSION=$ELK_VERSION

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
