ARG ELK_VERSION
FROM docker.elastic.co/kibana/kibana:$ELK_VERSION
# https://github.com/elastic/kibana-docker

# make ELK_VERSION available in later commands:
#ARG ELK_VERSION
#ENV ELK_VERSION=$ELK_VERSION
#RUN echo "env var for ELK_VERSION = $ELK_VERSION"

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
