ARG ELK_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
# https://github.com/elastic/elasticsearch-docker

# make ELK_VERSION available in later commands:
#ARG ELK_VERSION
#ENV ELK_VERSION=$ELK_VERSION
#RUN echo "env var for ELK_VERSION = $ELK_VERSION"

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
