ARG ELK_VERSION=5.6.3
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
# https://github.com/elastic/elasticsearch-docker

ARG ELK_VERSION
ENV ELK_VERSION=$ELK_VERSION

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
