ARG ELK_VERSION
FROM docker.elastic.co/logstash/logstash:$ELK_VERSION
# https://github.com/elastic/logstash-docker

# make ELK_VERSION available in later commands:
#ARG ELK_VERSION
#ENV ELK_VERSION=$ELK_VERSION
#RUN echo "env var for ELK_VERSION = $ELK_VERSION"

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
# RUN logstash-plugin install logstash-filter-json
