ARG ELK_VERSION=5.6.3
FROM docker.elastic.co/logstash/logstash:$ELK_VERSION
# https://github.com/elastic/logstash-docker

ARG ELK_VERSION
ENV ELK_VERSION=$ELK_VERSION

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
